<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Ingresar</name>
   <tag></tag>
   <elementGuidId>bc089db0-291e-4e1b-a3dd-3d926fe04a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.form-button.btn.btn-login.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e3ec210-6740-490e-98c8-8797552d3160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ca4113b1-f137-4385-9e1d-6f416d96c28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>login-button</value>
      <webElementGuid>cf2436cc-bb24-4a0e-abcb-e60a1594037c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button btn btn-login btn-primary</value>
      <webElementGuid>bb73e218-db2f-40de-a305-10e5f26d3c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>LC.login == true ? 'btn btn-primary btn-login':'btn btn-login btn-disabled'</value>
      <webElementGuid>90560984-7807-4f68-acb4-6de2c40df00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ingresar
                        </value>
      <webElementGuid>ef27aca1-ccc6-404c-939e-ddadcaf82c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;content&quot;]/main[1]/div[@class=&quot;container-login-form&quot;]/ng-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;row container-main ng-scope&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;row container-main-form&quot;]/form[@class=&quot;form-horizontal ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;container-well&quot;]/div[@class=&quot;row container-button-login&quot;]/button[@class=&quot;form-button btn btn-login btn-primary&quot;]</value>
      <webElementGuid>ce8a2a65-4a13-4cc8-9674-8e94fb273aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>1a9aad23-3e6f-4dce-87cb-402f989278f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/main/div/ng-view/div/div/div/form/div/div[5]/button</value>
      <webElementGuid>482c1f01-0c5e-4c19-8717-143472d350f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contraseña'])[1]/following::button[1]</value>
      <webElementGuid>728d9a81-6da2-43ea-8e5f-e894cc494e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario'])[1]/following::button[1]</value>
      <webElementGuid>7cead886-1977-473d-8359-2e58a833be60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresar']/parent::*</value>
      <webElementGuid>00b82195-d75c-4606-aa2f-dac6d19fe5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7f349e30-e1b2-4e47-9df1-f19303b6ce8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                        Ingresar
                        ' or . = '
                        Ingresar
                        ')]</value>
      <webElementGuid>6640804d-a8d9-4603-a9d0-555c5bdd4ddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
