<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Username</name>
   <tag></tag>
   <elementGuidId>a687fbcb-d30d-4f51-aed8-9cb173b5b216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8a42030-e979-4efc-bffc-2a42da2efc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9efd85ea-738c-4317-82cc-47c671dd603f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>7805b2c0-ec42-4f82-922b-539f15b326c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>f8aa93b0-ee8f-4dc4-8b5f-0f22e4df4bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>7fb896bf-8efd-4633-8cb8-f877db8bfbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>user-input</value>
      <webElementGuid>5e8ae4da-4aef-48c4-b10d-04ee4babe4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>LC.usuario.username</value>
      <webElementGuid>a3e9c7c9-b025-4c70-88c7-18dfdcc107ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[LC.error == true ? 'alert-danger-login' : '' , LC.usuario.username == '' ? '' : LC.checkLog() ]</value>
      <webElementGuid>b364f404-9580-402b-8fb7-5b1ccacaaa77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6d24f5f-2746-4036-a915-b3bb9cf6cba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;content&quot;]/main[1]/div[@class=&quot;container-login-form&quot;]/ng-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;row container-main ng-scope&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;row container-main-form&quot;]/form[@class=&quot;form-horizontal ng-pristine ng-valid ng-valid-maxlength&quot;]/div[@class=&quot;container-well&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-login&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength&quot;]</value>
      <webElementGuid>e22fbd12-43c8-4341-9dc6-d85a28ab3df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user']</value>
      <webElementGuid>5c68ba34-c775-4099-8ea2-3e27dd4a7807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/main/div/ng-view/div/div/div/form/div/div[3]/div/input</value>
      <webElementGuid>62e3e59f-6518-4d9c-8536-1bac74438bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f341085-7b54-4ffd-836a-0f2a2983bf5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user']</value>
      <webElementGuid>dd7f6efa-fc64-4d4e-962f-3c89194b4e42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
