<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_BuscarAfiliado</name>
   <tag></tag>
   <elementGuidId>c3651fe2-1257-412c-a5e1-ef5d2e8833c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnBuscarConsultAfiliado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnBuscarConsultAfiliado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c103633d-e445-4950-b3b3-c2c7cd42fa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnBuscarConsultAfiliado</value>
      <webElementGuid>cfcb68b6-0d1f-432e-a30d-38d61646a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>affiliate-search-button</value>
      <webElementGuid>6f1c9557-371c-43a6-9093-982dfc1ec770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c49a440d-14a6-450b-94f6-e720c5d0f0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-container--item button btn btn-primary</value>
      <webElementGuid>7b5a4807-d7db-45b8-9c01-78ac81d5dc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>basicSearchForm.surName.$error.pattern || basicSearchForm.lastName.$error.pattern
                        || basicSearchForm.secondName.$error.pattern || basicSearchForm.firstName.$error.pattern
                        || basicSearchForm.idBDUA.$error.pattern || basicSearchForm.documentInput.$error.pattern || ABS.searching</value>
      <webElementGuid>eff1f495-3ed8-4135-8853-0e9414e1c3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Buscar
              </value>
      <webElementGuid>ceef6896-e16d-4f6d-a1b9-fe1652f24c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnBuscarConsultAfiliado&quot;)</value>
      <webElementGuid>130ba4cb-e737-47de-ab79-6f4794ac93ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnBuscarConsultAfiliado']</value>
      <webElementGuid>78a1470e-b227-49db-b885-4a016ab62301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/main/div[2]/ng-view/form/div/section[2]/div[2]/button</value>
      <webElementGuid>9ddd879e-44e9-4bfd-8d87-73f3362a30ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apellidos y Nombres'])[1]/following::button[1]</value>
      <webElementGuid>33cc007e-0e3e-4f12-879d-85945bc912f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID BDUA'])[1]/following::button[1]</value>
      <webElementGuid>624455ff-472b-4b55-974e-d4e23d5cf664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/preceding::button[1]</value>
      <webElementGuid>331885e8-7200-4cf8-8fe4-7bc0c48665ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione los filtros deseados para obtener resultados'])[1]/preceding::button[2]</value>
      <webElementGuid>1d88fff6-164b-4d7e-9bfa-2310c436127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>c0fc1fea-abe3-4d56-a361-6e2fe0766847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>af24c046-cd11-4462-af37-1dcdd5a6905d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnBuscarConsultAfiliado' and @type = 'submit' and (text() = '
                Buscar
              ' or . = '
                Buscar
              ')]</value>
      <webElementGuid>aee49d68-7911-48f1-a6d9-90f7c5df7e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
