<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_NroDoc</name>
   <tag></tag>
   <elementGuidId>5176a385-d229-4615-982c-a31775fdab1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputNoDocumentoConsultAfiliado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNoDocumentoConsultAfiliado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d35d979-862d-44e5-8bb7-c48c32262c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNoDocumentoConsultAfiliado</value>
      <webElementGuid>ad9034c6-9166-419e-bcf7-5e23db688f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>affiliate-document-input</value>
      <webElementGuid>716c5a69-0e82-455d-b91a-473a7c95b891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>documentInput</value>
      <webElementGuid>9b3a14bb-5b5c-4323-9543-ef060c88f0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12342c25-2fb3-4585-831e-7ff8364e485c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mi-class ng-pristine ng-valid ng-empty ng-valid-pattern ng-valid-maxlength ng-touched</value>
      <webElementGuid>513d3767-3724-4d31-9f83-eac1cd04a116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>feb718ee-b069-4f15-923a-b21ac617da6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ABS.changeDocumentType()</value>
      <webElementGuid>89cf51f9-cc7f-4b0f-b251-ee4fb61c9e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ABS.afiliado.documento.numero</value>
      <webElementGuid>9ce25d7b-e724-4acc-8d03-691dea9c6bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>ABS.searching</value>
      <webElementGuid>91c3292c-188e-4d9f-b082-321750188e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5044ac29-b03b-4eb4-90dc-413d14f744d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputNoDocumentoConsultAfiliado&quot;)</value>
      <webElementGuid>a7010092-fcc4-416d-ac06-869839200140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNoDocumentoConsultAfiliado']</value>
      <webElementGuid>2ceb8e85-73bf-4a5b-ba85-dbfb2f97403b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/main/div[2]/ng-view/form/div/section[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>76475fa8-30cd-4f12-ab9c-e0ac3d5f1207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1bb4ec8b-674a-4445-8312-e891c876f5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputNoDocumentoConsultAfiliado' and @name = 'documentInput' and @type = 'text']</value>
      <webElementGuid>144d45f5-d928-4c71-aaac-21a22732ee54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
